### ISSUE TITLE
Binder link broken

### ISSUE THREAD

**Issue by TAdeJong** [Energya/cma-es-configuration-data-mining#1]
Are you aware the binder link in the readme is broken? Seems to be some python2/python3 issue with scikit-learn.

**Comment by sjvrijn** [comment]
Thanks for reporting, fixed it in f67c107 by limiting the `scikit-learn` version to <=20.3, as >=0.21 requires python 3.5+.

I'll keep this issue open for now until I've got all imports working on binder (especially `pydot` seems to be another issue)

**Comment by TAdeJong** [comment]
FYI: It now seems to build, but fails to launch for me.

**Comment by sjvrijn** [comment]
@TAdeJong The fix was still a WIP when you tested it ;)
Complete and verified fix now online with 78844f3
